


mongodb.url=mongodb://localhost:27017/ycsb # MongoDB connection string
mongodb.database=ycsb # Database name
mongodb.collection=usertable # Collection name
mongodb.writeConcern=acknowledged # Write concern level
#mongodb.writeConcern=majority
mongodb.readConcern=local # Read concern level
mongodb.readPreference=